
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Dec 03 20:50:55 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 8;
  public static final int IDENT = 2;
  public static final int PLUS = 11;
  public static final int LESS_EQUAL = 18;
  public static final int LARGER_EQUAL = 16;
  public static final int SEMI = 23;
  public static final int NOT_EQUAL = 14;
  public static final int LARGER_THAN = 15;
  public static final int NUM_CONST = 3;
  public static final int BOOL_CONST = 5;
  public static final int MODULO = 10;
  public static final int BRACES_END = 21;
  public static final int BRACES_BEGIN = 20;
  public static final int EQUALS = 13;
  public static final int COMMA = 6;
  public static final int EOF = 0;
  public static final int DIVIDE = 9;
  public static final int LESS_THAN = 17;
  public static final int PROG = 7;
  public static final int MINUS = 12;
  public static final int CONST = 22;
  public static final int error = 1;
  public static final int ASSIGN = 19;
  public static final int CHAR_CONST = 4;
}

