
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Dec 21 22:57:44 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 4;
  public static final int DIVIDE = 9;
  public static final int INCREMENT = 40;
  public static final int CONST = 26;
  public static final int PARENTHESES_BEGIN = 24;
  public static final int EQUALS = 13;
  public static final int CASE = 46;
  public static final int NOT_EQUAL = 14;
  public static final int SEMI = 27;
  public static final int CONTINUE = 34;
  public static final int NUM_CONST = 3;
  public static final int DECREMENT = 41;
  public static final int MINUS = 12;
  public static final int AND = 38;
  public static final int OR = 36;
  public static final int COMMA = 6;
  public static final int CLASS = 28;
  public static final int LESS_EQUAL = 18;
  public static final int BRACKET_END = 23;
  public static final int PLUS = 11;
  public static final int MULTIPLY = 8;
  public static final int ASSIGN = 19;
  public static final int BRACES_BEGIN = 20;
  public static final int IF = 31;
  public static final int DOT = 39;
  public static final int EOF = 0;
  public static final int RETURN = 35;
  public static final int PARENTHESES_END = 25;
  public static final int NEW = 37;
  public static final int error = 1;
  public static final int MODULO = 10;
  public static final int BREAK = 33;
  public static final int IDENT = 2;
  public static final int VOID = 30;
  public static final int BRACES_END = 21;
  public static final int SWITCH = 45;
  public static final int COLON = 47;
  public static final int ELSE = 32;
  public static final int BRACKET_BEGIN = 22;
  public static final int READ = 48;
  public static final int WHILE = 44;
  public static final int LARGER_EQUAL = 16;
  public static final int LARGER_THAN = 15;
  public static final int EXTENDS = 29;
  public static final int PROG = 7;
  public static final int BOOL_CONST = 5;
  public static final int LESS_THAN = 17;
  public static final int DO = 43;
  public static final int PRINT = 42;
}

