
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 20 15:40:23 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 6;
  public static final int DIVIDE = 11;
  public static final int INCREMENT = 42;
  public static final int CONST = 28;
  public static final int PARENTHESES_BEGIN = 26;
  public static final int EQUALS = 15;
  public static final int CASE = 48;
  public static final int NOT_EQUAL = 16;
  public static final int CONTINUE = 36;
  public static final int SEMI = 29;
  public static final int NUM_CONST = 5;
  public static final int DECREMENT = 43;
  public static final int MINUS = 14;
  public static final int AND = 40;
  public static final int OR = 38;
  public static final int COMMA = 8;
  public static final int CLASS = 30;
  public static final int QUESTION_MARK = 51;
  public static final int LESS_EQUAL = 20;
  public static final int BRACKET_END = 25;
  public static final int PLUS = 13;
  public static final int MULTIPLY = 10;
  public static final int ASSIGN = 21;
  public static final int BRACES_BEGIN = 22;
  public static final int IF = 33;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int RETURN = 37;
  public static final int PARENTHESES_END = 27;
  public static final int NEW = 39;
  public static final int error = 1;
  public static final int MODULO = 12;
  public static final int BREAK = 35;
  public static final int IDENT = 2;
  public static final int VOID = 32;
  public static final int BRACES_END = 23;
  public static final int SWITCH = 47;
  public static final int COLON = 49;
  public static final int ELSE = 34;
  public static final int BRACKET_BEGIN = 24;
  public static final int READ = 50;
  public static final int GOTO = 3;
  public static final int WHILE = 46;
  public static final int FINAL = 4;
  public static final int LARGER_EQUAL = 18;
  public static final int LARGER_THAN = 17;
  public static final int EXTENDS = 31;
  public static final int PROG = 9;
  public static final int BOOL_CONST = 7;
  public static final int LESS_THAN = 19;
  public static final int DO = 45;
  public static final int PRINT = 44;
}

