Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test1.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: 1 2 a b true false"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test1.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test2.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: 1 2 a b true false"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test2.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test3.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: 1 2 a b true false"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test3.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test4.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: 111    222   aaa   bbb   true true true    false false false"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test4.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test5.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: 1 2 a b true false"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test5.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test6.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: 1 2 a b true false"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test6.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test7.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: 1 2 a b true false"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test7.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test9.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: 1    2   a   b   true    false |---| 3   4   c   d   false   true"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test9.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test10.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: 1        char        true"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test10.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test11.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result:  99  true 1000  false |   0  false|"
Write-Output "For input: true 99 1000"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test11.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test12.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result:   77a false   0  false   0  false"
Write-Output "For input: a 77"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test12.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test13.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result:    2  false   0  true   0  false"
Write-Output "For input: true"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test13.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test14.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: | 1251000| 125| 250|   0|12456|  30| -12|"
Write-Output "For input: 25 100"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test14.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test15.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: 0 640"
Write-Output "For input: 25 100 200 66"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test15.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test16.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: -32"
Write-Output "For input: 53 81 66 10"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test16.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test17.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: t 3 f 3"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test17.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test18.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: ???"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test18.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test19.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: 103"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test19.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test20.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: Nothing"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test20.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test21.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: Nothing"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test21.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test22.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: Nothing"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test22.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test23.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: Nothjing"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test23.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test24.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: Nothing"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test24.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test26.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: 3 1 "
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test26.obj
Write-Output ""
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "test27.obj"
Write-Output "--------------------------------------------------------------"
Write-Output "--------------------------------------------------------------"
Write-Output "Expected result: 9999"
java -cp lib\mj-runtime.jar rs.etf.pp1.mj.runtime.Run test/test27.obj
Write-Host -NoNewLine 'Press any key to continue...';
$null = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown');