java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test1.mj test/test1.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test2.mj test/test2.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test3.mj test/test3.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test4.mj test/test4.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test5.mj test/test5.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test6.mj test/test6.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test7.mj test/test7.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test8.mj test/test8.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test9.mj test/test9.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test10.mj test/test10.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test11.mj test/test11.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test12.mj test/test12.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test13.mj test/test13.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test14.mj test/test14.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test15.mj test/test15.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test16.mj test/test16.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test17.mj test/test17.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test18.mj test/test18.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test19.mj test/test19.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test20.mj test/test20.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test21.mj test/test21.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test22.mj test/test22.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test23.mj test/test23.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test24.mj test/test24.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test25.mj test/test25.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test26.mj test/test26.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test27.mj test/test27.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test1_error.mj test/test1_error.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test2_error.mj test/test2_error.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test3_error.mj test/test3_error.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test4_error.mj test/test4_error.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test5_error.mj test/test5_error.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test6_error.mj test/test6_error.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test7_error.mj test/test7_error.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test8_error.mj test/test8_error.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test9_error.mj test/test9_error.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test10_error.mj test/test10_error.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test11_error.mj test/test11_error.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test12_error.mj test/test12_error.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test13_error.mj test/test13_error.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test14_error.mj test/test14_error.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test15_error.mj test/test15_error.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test16_error.mj test/test16_error.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test17_error.mj test/test17_error.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test18_error.mj test/test18_error.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test19_error.mj test/test19_error.obj
java -classpath "./bin;./lib/cup_v10k.jar;./lib/JFlex.jar;./lib/log4j-1.2.17.jar;./lib/symboltable-1-1.jar;./lib/mj-runtime.jar" rs.ac.bg.etf.pp1.Compiler test/testovi/test20_error.mj test/test20_error.obj
Write-Host -NoNewLine 'Press any key to continue...';
$null = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown');
